#!/usr/bin/env bash
# 00-bootstrap.sh — one-time setup of shared infrastructure
#
# Creates:
#   * DB Subnet Group covering the default VPC's public subnets
#   * Security Group allowing inbound 4488 (Aurora port) from itself
#   * EC2 key pair (saved as state/abt-test-key.pem)
#
# Idempotent: safe to re-run; will not duplicate resources.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFRA_DIR="$REPO_ROOT/infra"
STATE_DIR="$INFRA_DIR/state"
mkdir -p "$STATE_DIR"

export AWS_PROFILE="${AWS_PROFILE:-jiasunm-neo}"
export AWS_REGION="${AWS_REGION:-us-east-1}"

aws_() { aws --profile "$AWS_PROFILE" --region "$AWS_REGION" "$@"; }

echo "============================================================"
echo " Aurora BG Toolkit — bootstrap shared infra"
echo "  profile: $AWS_PROFILE   region: $AWS_REGION"
echo "============================================================"

# 1) Find default VPC
VPC_ID=$(aws_ ec2 describe-vpcs --filters "Name=isDefault,Values=true" \
    --query 'Vpcs[0].VpcId' --output text)
[[ "$VPC_ID" == "None" || -z "$VPC_ID" ]] && { echo "no default VPC"; exit 1; }
echo "vpc:           $VPC_ID"

# 2) Find default subnets in all AZs
SUBNETS=$(aws_ ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$VPC_ID" "Name=default-for-az,Values=true" \
    --query 'Subnets[].SubnetId' --output text)
echo "subnets:       $SUBNETS"

# 3) Create or find DB subnet group
DB_SUBNET_GROUP="abt-test-subnets"
if ! aws_ rds describe-db-subnet-groups \
        --db-subnet-group-name "$DB_SUBNET_GROUP" >/dev/null 2>&1; then
    aws_ rds create-db-subnet-group \
        --db-subnet-group-name "$DB_SUBNET_GROUP" \
        --db-subnet-group-description "Aurora BG Toolkit shared subnets" \
        --subnet-ids $SUBNETS >/dev/null
    echo "db subnet grp: $DB_SUBNET_GROUP (created)"
else
    echo "db subnet grp: $DB_SUBNET_GROUP (existing)"
fi

# 4) Create or find security group
SG_NAME="abt-test-sg"
SG_ID=$(aws_ ec2 describe-security-groups \
    --filters "Name=vpc-id,Values=$VPC_ID" "Name=group-name,Values=$SG_NAME" \
    --query 'SecurityGroups[0].GroupId' --output text)
if [[ "$SG_ID" == "None" || -z "$SG_ID" ]]; then
    SG_ID=$(aws_ ec2 create-security-group \
        --group-name "$SG_NAME" \
        --description "Aurora BG Toolkit test traffic" \
        --vpc-id "$VPC_ID" --query 'GroupId' --output text)
    echo "sg:            $SG_ID (created)"

    # Allow port 4488 from within the SG itself (so EC2 can reach Aurora)
    aws_ ec2 authorize-security-group-ingress \
        --group-id "$SG_ID" --protocol tcp --port 4488 \
        --source-group "$SG_ID" >/dev/null

    # Allow SSH from anywhere (we're going to use EC2 Instance Connect, but
    # keeping inbound 22 helps for plain ssh fallback)
    aws_ ec2 authorize-security-group-ingress \
        --group-id "$SG_ID" --protocol tcp --port 22 \
        --cidr 0.0.0.0/0 >/dev/null
    echo "sg ingress:    4488 (self), 22 (0.0.0.0/0)"
else
    echo "sg:            $SG_ID (existing)"
fi

# 5) Create or find EC2 key pair
KEY_NAME="abt-test-key"
KEY_FILE="$STATE_DIR/$KEY_NAME.pem"
if ! aws_ ec2 describe-key-pairs --key-names "$KEY_NAME" >/dev/null 2>&1; then
    aws_ ec2 create-key-pair --key-name "$KEY_NAME" \
        --query 'KeyMaterial' --output text > "$KEY_FILE"
    chmod 600 "$KEY_FILE"
    echo "key pair:      $KEY_NAME (created, saved to $KEY_FILE)"
else
    echo "key pair:      $KEY_NAME (existing — reusing)"
    if [[ ! -f "$KEY_FILE" ]]; then
        echo "  WARNING: $KEY_FILE missing locally; you can't SSH unless you have it"
    fi
fi

# 6) Latest Amazon Linux 2023 AMI (for the EC2 client)
AMI_ID=$(aws_ ec2 describe-images \
    --owners amazon \
    --filters \
        "Name=name,Values=al2023-ami-2023.*-x86_64" \
        "Name=state,Values=available" \
        "Name=architecture,Values=x86_64" \
    --query 'sort_by(Images, &CreationDate)[-1].ImageId' --output text)
echo "AL2023 AMI:    $AMI_ID"

# 7) Persist state
cat > "$STATE_DIR/bootstrap.env" <<EOF
# Sourced by other infra scripts. Generated by 00-bootstrap.sh.
export ABT_VPC_ID="$VPC_ID"
export ABT_DB_SUBNET_GROUP="$DB_SUBNET_GROUP"
export ABT_SG_ID="$SG_ID"
export ABT_KEY_NAME="$KEY_NAME"
export ABT_KEY_FILE="$KEY_FILE"
export ABT_AMI_ID="$AMI_ID"
export AWS_PROFILE="$AWS_PROFILE"
export AWS_REGION="$AWS_REGION"
EOF

echo
echo "Bootstrap state saved to $STATE_DIR/bootstrap.env"
echo "Source it from later scripts:  source $STATE_DIR/bootstrap.env"
