#!/usr/bin/env bash
# 11-record-cluster-state.sh — once a cluster is fully available, capture its
# endpoint + master-secret-arn into state/<cluster-name>.env
#
# Usage: ./11-record-cluster-state.sh <cluster-name>

set -euo pipefail

CLUSTER_NAME="${1:?usage: $0 <cluster-name>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE_DIR="$REPO_ROOT/infra/state"
source "$STATE_DIR/bootstrap.env"

aws_() { aws --profile "$AWS_PROFILE" --region "$AWS_REGION" "$@"; }

DESCRIBE=$(aws_ rds describe-db-clusters --db-cluster-identifier "$CLUSTER_NAME" --query 'DBClusters[0]')

ENDPOINT=$(echo "$DESCRIBE" | python3 -c 'import sys,json; print(json.load(sys.stdin)["Endpoint"])')
READER_ENDPOINT=$(echo "$DESCRIBE" | python3 -c 'import sys,json; print(json.load(sys.stdin)["ReaderEndpoint"])')
SECRET_ARN=$(echo "$DESCRIBE" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("MasterUserSecret",{}).get("SecretArn",""))')

[[ -z "$SECRET_ARN" ]] && { echo "MasterUserSecret not yet present; cluster may still be provisioning"; exit 1; }

cat > "$STATE_DIR/${CLUSTER_NAME}.env" <<EOF
# Generated by 11-record-cluster-state.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
export ABT_CLUSTER_NAME="$CLUSTER_NAME"
export ABT_CLUSTER_ENDPOINT="$ENDPOINT"
export ABT_CLUSTER_READER_ENDPOINT="$READER_ENDPOINT"
export ABT_CLUSTER_SECRET_ARN="$SECRET_ARN"
EOF
echo "wrote $STATE_DIR/${CLUSTER_NAME}.env"
cat "$STATE_DIR/${CLUSTER_NAME}.env"
